services:
  app:
    build:
      context: .  # Đảm bảo dấu cách ở đây
      dockerfile: Dockerfile
    container_name: nodejs_app
    ports:
      - "6000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/travel-with-me
      - MYSQL_HOST=mysql # Chỉnh sửa ở đây
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Vanh28082004@
      - MYSQL_DATABASE=Travel
      - REDIS_HOST=redis
      - RABBITMQ_URI=amqp://rabbitmq # Chỉnh sửa ở đây
      
    depends_on:
      - mongo
      - mysql
      - redis
      - rabbitmq
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Vanh28082004@
      MYSQL_DATABASE: Travel
      
    ports:
      - "4306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 

volumes:
  mongo_data:
  mysql_data:
